In [14]:
import pandas as pd
from function import csv_to_data,calc_dist
import matplotlib.pyplot as plt
import numpy as np

ImportError: cannot import name 'calc_dist' from 'function' (/Users/fusawayugo/Desktop/class/人工知能演習/ai_experiment/dot_matching/function.py)

In [13]:
#north
x,y,lum,HIPnum=csv_to_data('../star_data/north.csv')
data = np.column_stack((x,y,lum,HIPnum))
position=np.column_stack((x,y))
edge_dist={}
for i in range(len(data)):
    edge_dist[HIPnum[i]]=[]
    for j in range(len(data)):
        if i==j:
            continue
        




[[ 1.06235437e+00  3.88774061e-02  2.07000000e+00  6.77000000e+02]
 [ 5.37999571e-01  2.15299203e-02  2.28000000e+00  7.46000000e+02]
 [ 1.30361613e+00  7.53562684e-02  2.83000000e+00  1.06700000e+03]
 ...
 [ 1.46693934e+00 -1.28770555e-01  4.13000000e+00  1.16771000e+05]
 [ 1.53499330e+00 -1.20581957e-01  4.49000000e+00  1.16928000e+05]
 [ 1.45099743e+00 -4.43183324e-03  4.03000000e+00  1.18268000e+05]]
